# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_buy_ticket_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BuyTicketWidget(object):
    def setupUi(self, BuyTicketWidget):
        BuyTicketWidget.setObjectName("BuyTicketWidget")
        BuyTicketWidget.resize(740, 436)
        self.verticalLayout = QtWidgets.QVBoxLayout(BuyTicketWidget)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(BuyTicketWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox_5)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout.addWidget(self.calendarWidget)
        self.groupSelectBtns = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupSelectBtns.setTitle("")
        self.groupSelectBtns.setObjectName("groupSelectBtns")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupSelectBtns)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnSelectAllDays = QtWidgets.QPushButton(self.groupSelectBtns)
        self.btnSelectAllDays.setObjectName("btnSelectAllDays")
        self.verticalLayout_2.addWidget(self.btnSelectAllDays)
        self.btnInvertSelectedDays = QtWidgets.QPushButton(self.groupSelectBtns)
        self.btnInvertSelectedDays.setObjectName("btnInvertSelectedDays")
        self.verticalLayout_2.addWidget(self.btnInvertSelectedDays)
        self.btnSelectAllWorkDays = QtWidgets.QPushButton(self.groupSelectBtns)
        self.btnSelectAllWorkDays.setObjectName("btnSelectAllWorkDays")
        self.verticalLayout_2.addWidget(self.btnSelectAllWorkDays)
        self.btnSelectAllWeekDays = QtWidgets.QPushButton(self.groupSelectBtns)
        self.btnSelectAllWeekDays.setObjectName("btnSelectAllWeekDays")
        self.verticalLayout_2.addWidget(self.btnSelectAllWeekDays)
        self.btnClear = QtWidgets.QPushButton(self.groupSelectBtns)
        self.btnClear.setObjectName("btnClear")
        self.verticalLayout_2.addWidget(self.btnClear)
        spacerItem = QtWidgets.QSpacerItem(20, 181, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupSelectBtns)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.listSelectedDays = QtWidgets.QListWidget(self.groupBox)
        self.listSelectedDays.setObjectName("listSelectedDays")
        self.horizontalLayout_4.addWidget(self.listSelectedDays)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_5)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.textSZBusCard = QtWidgets.QLineEdit(self.groupBox_5)
        self.textSZBusCard.setMaximumSize(QtCore.QSize(100, 16777215))
        self.textSZBusCard.setObjectName("textSZBusCard")
        self.horizontalLayout_2.addWidget(self.textSZBusCard)
        self.btnBuyTicket = QtWidgets.QPushButton(self.groupBox_5)
        self.btnBuyTicket.setObjectName("btnBuyTicket")
        self.horizontalLayout_2.addWidget(self.btnBuyTicket)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkAutoRefresh = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkAutoRefresh.setObjectName("checkAutoRefresh")
        self.horizontalLayout_3.addWidget(self.checkAutoRefresh)
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.textRefreshInterval = QtWidgets.QLineEdit(self.groupBox_5)
        self.textRefreshInterval.setMaximumSize(QtCore.QSize(100, 16777215))
        self.textRefreshInterval.setObjectName("textRefreshInterval")
        self.horizontalLayout_3.addWidget(self.textRefreshInterval)
        self.checkWeChatNotify = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkWeChatNotify.setObjectName("checkWeChatNotify")
        self.horizontalLayout_3.addWidget(self.checkWeChatNotify)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_5)

        self.retranslateUi(BuyTicketWidget)
        QtCore.QMetaObject.connectSlotsByName(BuyTicketWidget)

    def retranslateUi(self, BuyTicketWidget):
        _translate = QtCore.QCoreApplication.translate
        BuyTicketWidget.setWindowTitle(_translate("BuyTicketWidget", "Form"))
        self.groupBox_5.setTitle(_translate("BuyTicketWidget", "购票"))
        self.btnSelectAllDays.setText(_translate("BuyTicketWidget", "全选"))
        self.btnInvertSelectedDays.setText(_translate("BuyTicketWidget", "反选"))
        self.btnSelectAllWorkDays.setText(_translate("BuyTicketWidget", "全工作日"))
        self.btnSelectAllWeekDays.setText(_translate("BuyTicketWidget", "全周末"))
        self.btnClear.setText(_translate("BuyTicketWidget", "Clear"))
        self.groupBox.setTitle(_translate("BuyTicketWidget", "已选日期"))
        self.label.setText(_translate("BuyTicketWidget", "深圳通"))
        self.btnBuyTicket.setText(_translate("BuyTicketWidget", "购票"))
        self.checkAutoRefresh.setText(_translate("BuyTicketWidget", "自动刷票"))
        self.label_3.setText(_translate("BuyTicketWidget", "间隔(s):"))
        self.textRefreshInterval.setText(_translate("BuyTicketWidget", "10"))
        self.checkWeChatNotify.setText(_translate("BuyTicketWidget", "微信通知"))

