# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_remain_ticket_widget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_remainTicketWidget(object):
    def setupUi(self, remainTicketWidget):
        remainTicketWidget.setObjectName("remainTicketWidget")
        remainTicketWidget.resize(414, 439)
        self.verticalLayout = QtWidgets.QVBoxLayout(remainTicketWidget)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(remainTicketWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.tableTicketStatusIndicator = QtWidgets.QTableWidget(self.groupBox)
        self.tableTicketStatusIndicator.setMaximumSize(QtCore.QSize(300, 33))
        self.tableTicketStatusIndicator.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableTicketStatusIndicator.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableTicketStatusIndicator.setObjectName("tableTicketStatusIndicator")
        self.tableTicketStatusIndicator.setColumnCount(3)
        self.tableTicketStatusIndicator.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableTicketStatusIndicator.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTicketStatusIndicator.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTicketStatusIndicator.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTicketStatusIndicator.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableTicketStatusIndicator.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.tableTicketStatusIndicator.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setFlags(QtCore.Qt.ItemIsSelectable)
        self.tableTicketStatusIndicator.setItem(0, 2, item)
        self.tableTicketStatusIndicator.horizontalHeader().setVisible(False)
        self.tableTicketStatusIndicator.horizontalHeader().setHighlightSections(False)
        self.tableTicketStatusIndicator.verticalHeader().setVisible(False)
        self.tableTicketStatusIndicator.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.tableTicketStatusIndicator, 0, 0, 1, 1)
        self.calendarTicket = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarTicket.setFirstDayOfWeek(QtCore.Qt.Monday)
        self.calendarTicket.setGridVisible(True)
        self.calendarTicket.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarTicket.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.calendarTicket.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.calendarTicket.setNavigationBarVisible(True)
        self.calendarTicket.setDateEditEnabled(False)
        self.calendarTicket.setObjectName("calendarTicket")
        self.gridLayout.addWidget(self.calendarTicket, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkAutoRefresh = QtWidgets.QCheckBox(self.groupBox)
        self.checkAutoRefresh.setObjectName("checkAutoRefresh")
        self.horizontalLayout_5.addWidget(self.checkAutoRefresh)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.textRefreshInterval = QtWidgets.QLineEdit(self.groupBox)
        self.textRefreshInterval.setObjectName("textRefreshInterval")
        self.horizontalLayout_5.addWidget(self.textRefreshInterval)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(remainTicketWidget)
        QtCore.QMetaObject.connectSlotsByName(remainTicketWidget)

    def retranslateUi(self, remainTicketWidget):
        _translate = QtCore.QCoreApplication.translate
        remainTicketWidget.setWindowTitle(_translate("remainTicketWidget", "Form"))
        self.groupBox.setTitle(_translate("remainTicketWidget", "余票:"))
        item = self.tableTicketStatusIndicator.verticalHeaderItem(0)
        item.setText(_translate("remainTicketWidget", "1"))
        item = self.tableTicketStatusIndicator.horizontalHeaderItem(0)
        item.setText(_translate("remainTicketWidget", "1"))
        item = self.tableTicketStatusIndicator.horizontalHeaderItem(1)
        item.setText(_translate("remainTicketWidget", "2"))
        item = self.tableTicketStatusIndicator.horizontalHeaderItem(2)
        item.setText(_translate("remainTicketWidget", "3"))
        __sortingEnabled = self.tableTicketStatusIndicator.isSortingEnabled()
        self.tableTicketStatusIndicator.setSortingEnabled(False)
        item = self.tableTicketStatusIndicator.item(0, 0)
        item.setText(_translate("remainTicketWidget", "有票"))
        item = self.tableTicketStatusIndicator.item(0, 1)
        item.setText(_translate("remainTicketWidget", "无票"))
        item = self.tableTicketStatusIndicator.item(0, 2)
        item.setText(_translate("remainTicketWidget", "已购"))
        self.tableTicketStatusIndicator.setSortingEnabled(__sortingEnabled)
        self.checkAutoRefresh.setText(_translate("remainTicketWidget", "自动刷新"))
        self.label_4.setText(_translate("remainTicketWidget", "  间隔(s):"))
        self.textRefreshInterval.setText(_translate("remainTicketWidget", "10"))

